/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'determineNakshatra' : IDL.Func(
      [IDL.Float64],
      [
        IDL.Record({
          'remainingDegreesInCurrentPada' : IDL.Float64,
          'preciseLongitude' : IDL.Float64,
          'pada' : IDL.Nat,
          'nakshatraNumber' : IDL.Nat,
          'remainingDegreesInNakshatra' : IDL.Float64,
          'nakshatraName' : IDL.Text,
          'degreesUntilNextPada' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'determineNakshatra' : IDL.Func(
        [IDL.Float64],
        [
          IDL.Record({
            'remainingDegreesInCurrentPada' : IDL.Float64,
            'preciseLongitude' : IDL.Float64,
            'pada' : IDL.Nat,
            'nakshatraNumber' : IDL.Nat,
            'remainingDegreesInNakshatra' : IDL.Float64,
            'nakshatraName' : IDL.Text,
            'degreesUntilNextPada' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };