/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface CheckInEntry {
    restlessness?: bigint;
    dayOfYear: bigint;
    mood?: string;
    timestamp: Time;
    nakshatra: string;
    energy?: bigint;
}
export interface SleepLogEntry {
    dayOfYear: bigint;
    sleepNotes?: string;
    timestamp: Time;
    nakshatra: string;
}
export interface BirthChartData {
    moonNakshatra: string;
    birthDate: string;
    atmakarakaNakshatra: string;
}
export interface UserProfile {
    isPremium: boolean;
    name: string;
    email?: string;
}
export interface DreamLogEntry {
    dreamNotes?: string;
    dayOfYear: bigint;
    timestamp: Time;
    nakshatra: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    determineNakshatra(lunarLongitude: number): Promise<{
        remainingDegreesInCurrentPada: number;
        preciseLongitude: number;
        pada: bigint;
        nakshatraNumber: bigint;
        remainingDegreesInNakshatra: number;
        nakshatraName: string;
        degreesUntilNextPada: number;
    }>;
    getAllLogs(): Promise<{
        dreamLogs: Array<DreamLogEntry>;
        sleepLogs: Array<SleepLogEntry>;
        checkIns: Array<CheckInEntry>;
        birthChart?: BirthChartData;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentDayOfYearForCaller(): Promise<bigint>;
    getLogsByDay(dayOfYear: bigint): Promise<{
        dreamLogs: Array<DreamLogEntry>;
        sleepLogs: Array<SleepLogEntry>;
        checkIns: Array<CheckInEntry>;
    }>;
    getLogsByNakshatra(nakshatra: string): Promise<{
        dreamLogs: Array<DreamLogEntry>;
        sleepLogs: Array<SleepLogEntry>;
        checkIns: Array<CheckInEntry>;
    }>;
    getNakshtaraPatterns(): Promise<{
        checkInPatterns: Array<[string, CheckInEntry]>;
        dreamPatterns: Array<[string, DreamLogEntry]>;
        sleepLogPatterns: Array<[string, SleepLogEntry]>;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveBirthChart(birthDate: string, moonNakshatra: string, atmakarakaNakshatra: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCheckIn(dayOfYear: bigint, nakshatra: string, mood: string | null, energy: bigint | null, restlessness: bigint | null): Promise<void>;
    saveDreamLog(dayOfYear: bigint, nakshatra: string, dreamNotes: string | null): Promise<void>;
    saveSleepLog(dayOfYear: bigint, nakshatra: string, sleepNotes: string | null): Promise<void>;
}
import type { BirthChartData as _BirthChartData, CheckInEntry as _CheckInEntry, DreamLogEntry as _DreamLogEntry, SleepLogEntry as _SleepLogEntry, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async determineNakshatra(arg0: number): Promise<{
        remainingDegreesInCurrentPada: number;
        preciseLongitude: number;
        pada: bigint;
        nakshatraNumber: bigint;
        remainingDegreesInNakshatra: number;
        nakshatraName: string;
        degreesUntilNextPada: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.determineNakshatra(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.determineNakshatra(arg0);
            return result;
        }
    }
    async getAllLogs(): Promise<{
        dreamLogs: Array<DreamLogEntry>;
        sleepLogs: Array<SleepLogEntry>;
        checkIns: Array<CheckInEntry>;
        birthChart?: BirthChartData;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLogs();
                return from_candid_record_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLogs();
            return from_candid_record_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentDayOfYearForCaller(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentDayOfYearForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentDayOfYearForCaller();
            return result;
        }
    }
    async getLogsByDay(arg0: bigint): Promise<{
        dreamLogs: Array<DreamLogEntry>;
        sleepLogs: Array<SleepLogEntry>;
        checkIns: Array<CheckInEntry>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogsByDay(arg0);
                return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogsByDay(arg0);
            return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogsByNakshatra(arg0: string): Promise<{
        dreamLogs: Array<DreamLogEntry>;
        sleepLogs: Array<SleepLogEntry>;
        checkIns: Array<CheckInEntry>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogsByNakshatra(arg0);
                return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogsByNakshatra(arg0);
            return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNakshtaraPatterns(): Promise<{
        checkInPatterns: Array<[string, CheckInEntry]>;
        dreamPatterns: Array<[string, DreamLogEntry]>;
        sleepLogPatterns: Array<[string, SleepLogEntry]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getNakshtaraPatterns();
                return from_candid_record_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNakshtaraPatterns();
            return from_candid_record_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveBirthChart(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBirthChart(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBirthChart(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCheckIn(arg0: bigint, arg1: string, arg2: string | null, arg3: bigint | null, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCheckIn(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCheckIn(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async saveDreamLog(arg0: bigint, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDreamLog(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDreamLog(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveSleepLog(arg0: bigint, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSleepLog(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSleepLog(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_CheckInEntry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckInEntry): CheckInEntry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DreamLogEntry_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DreamLogEntry): DreamLogEntry {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SleepLogEntry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SleepLogEntry): SleepLogEntry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BirthChartData]): BirthChartData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dayOfYear: bigint;
    sleepNotes: [] | [string];
    timestamp: _Time;
    nakshatra: string;
}): {
    dayOfYear: bigint;
    sleepNotes?: string;
    timestamp: Time;
    nakshatra: string;
} {
    return {
        dayOfYear: value.dayOfYear,
        sleepNotes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.sleepNotes)),
        timestamp: value.timestamp,
        nakshatra: value.nakshatra
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    restlessness: [] | [bigint];
    dayOfYear: bigint;
    mood: [] | [string];
    timestamp: _Time;
    nakshatra: string;
    energy: [] | [bigint];
}): {
    restlessness?: bigint;
    dayOfYear: bigint;
    mood?: string;
    timestamp: Time;
    nakshatra: string;
    energy?: bigint;
} {
    return {
        restlessness: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.restlessness)),
        dayOfYear: value.dayOfYear,
        mood: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.mood)),
        timestamp: value.timestamp,
        nakshatra: value.nakshatra,
        energy: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.energy))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isPremium: boolean;
    name: string;
    email: [] | [string];
}): {
    isPremium: boolean;
    name: string;
    email?: string;
} {
    return {
        isPremium: value.isPremium,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dreamLogs: Array<_DreamLogEntry>;
    sleepLogs: Array<_SleepLogEntry>;
    checkIns: Array<_CheckInEntry>;
}): {
    dreamLogs: Array<DreamLogEntry>;
    sleepLogs: Array<SleepLogEntry>;
    checkIns: Array<CheckInEntry>;
} {
    return {
        dreamLogs: from_candid_vec_n4(_uploadFile, _downloadFile, value.dreamLogs),
        sleepLogs: from_candid_vec_n8(_uploadFile, _downloadFile, value.sleepLogs),
        checkIns: from_candid_vec_n11(_uploadFile, _downloadFile, value.checkIns)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    checkInPatterns: Array<[string, _CheckInEntry]>;
    dreamPatterns: Array<[string, _DreamLogEntry]>;
    sleepLogPatterns: Array<[string, _SleepLogEntry]>;
}): {
    checkInPatterns: Array<[string, CheckInEntry]>;
    dreamPatterns: Array<[string, DreamLogEntry]>;
    sleepLogPatterns: Array<[string, SleepLogEntry]>;
} {
    return {
        checkInPatterns: from_candid_vec_n23(_uploadFile, _downloadFile, value.checkInPatterns),
        dreamPatterns: from_candid_vec_n25(_uploadFile, _downloadFile, value.dreamPatterns),
        sleepLogPatterns: from_candid_vec_n27(_uploadFile, _downloadFile, value.sleepLogPatterns)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dreamLogs: Array<_DreamLogEntry>;
    sleepLogs: Array<_SleepLogEntry>;
    checkIns: Array<_CheckInEntry>;
    birthChart: [] | [_BirthChartData];
}): {
    dreamLogs: Array<DreamLogEntry>;
    sleepLogs: Array<SleepLogEntry>;
    checkIns: Array<CheckInEntry>;
    birthChart?: BirthChartData;
} {
    return {
        dreamLogs: from_candid_vec_n4(_uploadFile, _downloadFile, value.dreamLogs),
        sleepLogs: from_candid_vec_n8(_uploadFile, _downloadFile, value.sleepLogs),
        checkIns: from_candid_vec_n11(_uploadFile, _downloadFile, value.checkIns),
        birthChart: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.birthChart))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dreamNotes: [] | [string];
    dayOfYear: bigint;
    timestamp: _Time;
    nakshatra: string;
}): {
    dreamNotes?: string;
    dayOfYear: bigint;
    timestamp: Time;
    nakshatra: string;
} {
    return {
        dreamNotes: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.dreamNotes)),
        dayOfYear: value.dayOfYear,
        timestamp: value.timestamp,
        nakshatra: value.nakshatra
    };
}
function from_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _CheckInEntry]): [string, CheckInEntry] {
    return [
        value[0],
        from_candid_CheckInEntry_n12(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _DreamLogEntry]): [string, DreamLogEntry] {
    return [
        value[0],
        from_candid_DreamLogEntry_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _SleepLogEntry]): [string, SleepLogEntry] {
    return [
        value[0],
        from_candid_SleepLogEntry_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CheckInEntry>): Array<CheckInEntry> {
    return value.map((x)=>from_candid_CheckInEntry_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _CheckInEntry]>): Array<[string, CheckInEntry]> {
    return value.map((x)=>from_candid_tuple_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _DreamLogEntry]>): Array<[string, DreamLogEntry]> {
    return value.map((x)=>from_candid_tuple_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _SleepLogEntry]>): Array<[string, SleepLogEntry]> {
    return value.map((x)=>from_candid_tuple_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DreamLogEntry>): Array<DreamLogEntry> {
    return value.map((x)=>from_candid_DreamLogEntry_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SleepLogEntry>): Array<SleepLogEntry> {
    return value.map((x)=>from_candid_SleepLogEntry_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isPremium: boolean;
    name: string;
    email?: string;
}): {
    isPremium: boolean;
    name: string;
    email: [] | [string];
} {
    return {
        isPremium: value.isPremium,
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
